<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJg0nFaa\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJg0nFaa/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJg0nFaa.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJg0nFaa\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJg0nFaa\appAppKernelProdContainer([
    'container.build_hash' => 'Jg0nFaa',
    'container.build_id' => '942affb8',
    'container.build_time' => 1733292002,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJg0nFaa');
